name: launch_tracker_app
description: App for imforming public about shuttle launches

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  retrofit: ^3.3.1
  injectable: ^2.1.0
  json_serializable: ^6.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  retrofit_generator: ^4.2.0

flutter:
  uses-material-design: true
