name: launch_tracker_app
description: App for imforming public about shuttle launches

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0-218.0.dev"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: 5.0.0
  retrofit: 4.0.1
  injectable: ^2.1.0
  easy_localization: ^3.0.1
  dartz: ^0.10.1
  provider: ^6.0.5
  get_it: ^7.2.0
  json_serializable: 6.6.1
  json_annotation: ^4.7.0
  share_plus: 6.3.1
  streaming_shared_preferences: ^2.0.0
  routemaster: ^1.0.1
  rxdart: ^0.27.7
  logger: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: 2.4.0
  retrofit_generator: 5.0.0
  injectable_generator: 2.1.4
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
